### PR TITLE
add typescript typings

### PR DESCRIPTION
**Pull request by RWOverdijk**
Using this locally in my project. Works pretty great.

Thanks for this component by the way, I use it everywhere.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@kohver Bump

**Comment by Berkays** [comment]
This would be great to have.

**Comment by RWOverdijk** [comment]
I'm forking this next time I check this PR and there's no feedback. 😄

But you can add them to your project for now.

**Comment by kohver** [comment]
Sorry for the long response, honestly I’m not really interested in this project now. But I do care about that nothing will break after merging, since I don’t work with Typescript. But looks like it’s almost impossible to break something by this, right?

I understand that it’s frustrating to contribute to a repository and don’t get any feedback for a long time. So I’m going to merge your PR and update the package version tomorrow. 

_sets a reminder_

**Comment by Berkays** [comment]
I use these type definitions without any problems. They should be safe to use.

**Comment by RWOverdijk** [comment]
No problem. I understand, I have a handful of repos like that myself.

But it's your own fault for making something cool 😄

**Pull request merged**
